name: bloc_dev_tools
description: The Remote DevTools package for `flutter_bloc` connects all Blocs to the Remote DevTools server, allowing developers to inspect changes in Bloc states and events during runtime.
version: 1.0.1
homepage: https://github.com/zakaria-525k/bloc_dev_tools

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  socketcluster_client: ^0.3.0
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

